name: contador_app
description: "Aplicativo de contagem para o trabalho."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.1.0
  uuid: ^4.0.0
  pdf: ^3.10.1
  printing: ^5.10.3
  path_provider: ^2.0.11
  share_plus: ^12.0.1
  image_picker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_foreground: "assets/icon/foreground.png"
  adaptive_icon_background: "assets/icon/background.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icon/